# Generated by Django 4.1.3 on 2023-04-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
