# Generated by Django 4.1.3 on 2023-04-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0004_order_product_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
