# Generated by Django 4.1.3 on 2023-04-02 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0007_remove_order_tags_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
