# Generated by Django 4.1.7 on 2023-04-06 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0009_bikedetails_usertag_alter_tag_name_rider_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_request_id', models.CharField(max_length=200, null=True)),
                ('created_at', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('points', models.IntegerField(null=True)),
                ('originAddress', models.CharField(max_length=200, null=True)),
                ('destinationAddress', models.CharField(max_length=200, null=True)),
                ('originLat', models.FloatField(null=True)),
                ('originLng', models.FloatField(null=True)),
                ('destinationLat', models.FloatField(null=True)),
                ('destinationLng', models.FloatField(null=True)),
                ('distance', models.FloatField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('passenger_name', models.CharField(max_length=200, null=True)),
                ('passenger_phone', models.CharField(max_length=200, null=True)),
                ('rider_name', models.CharField(max_length=200, null=True)),
                ('rider_phone', models.CharField(max_length=200, null=True)),
                ('rider_bike_number', models.CharField(max_length=200, null=True)),
                ('rider_bike_model', models.CharField(max_length=200, null=True)),
                ('rider_bike_color', models.CharField(max_length=200, null=True)),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redeem.passenger')),
                ('rider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redeem.rider')),
            ],
        ),
    ]
