# Generated by Django 4.1.7 on 2023-04-10 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0011_remove_rider_bike_details_rider_bike_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='bike_color',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='bike_model',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='bike_number',
        ),
        migrations.CreateModel(
            name='BikeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_number', models.CharField(max_length=200, null=True)),
                ('bike_model', models.CharField(max_length=200, null=True)),
                ('bike_color', models.CharField(max_length=200, null=True)),
                ('rider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redeem.rider')),
            ],
        ),
    ]
