# Generated by Django 4.1.7 on 2023-04-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0014_alter_order_status_orderrider_orderpassenger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='sos',
            options={'ordering': ['-created_at']},
        ),
    ]
